### ISSUE TITLE
alerview call ?

### ISSUE THREAD

**Issue by matrixreal** [finscn/Ejecta#12]
@finscn 
i try to call an alert view but always fails
how can i done it
whats the call please?

**Comment by matrixreal** [comment]
@finscn 
any news please ? hod do i call the alert view ?
thanks a lot

**Comment by finscn** [comment]
```
var alertView = new Ejecta.AlertView("title","message","cancelTitle","b1Title","b2Title");
alertView.addEventListener("dismiss",function(buttonIndex){
    console.log("You click button: "+buttonIndex);
});
alertView.show();
```

the "b1Title","b2Title" ... are optional

**Comment by matrixreal** [comment]
@finscn 
thanks thats work perfect
