### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by matrixreal** [finscn/Ejecta#24]
@finscn 
is there a way to encrypt the app folder (or images , sounds folder)
thanks

**Comment by finscn** [comment]
Yes. My fork includes  this feature.  I'll give you a example later

**Comment by lordnasty** [comment]
Yes please @finscn  .. i need too!
Anyway your fork is awesome!!

**Comment by finscn** [comment]
Hi, it's here : https://github.com/finscn/Ejecta/issues/25

**Comment by lordnasty** [comment]
Awesome! Thank you @finscn !!

**Comment by matrixreal** [comment]
@finscn 
awesome tooo !
thanks a lot
