### ISSUE TITLE
local notification ???

### ISSUE THREAD

**Issue by matrixreal** [finscn/Ejecta#3]
hi @finscn 
is your fork supporting local notification features ? (not push notification)
thanks

**Comment by finscn** [comment]
Yes,  see  EJBindingLocalNotification

**Comment by matrixreal** [comment]
and whats the call ? (message, game title and time) ?
and really ilike your fork it is magic ...

**Comment by finscn** [comment]
I found EJBindingLocalNotification can't run in iOS 8.  
Give some time to solve this problem.

By the way , are you working in KetchApp ?  If my game is done, could you publish it ? 
It's a pixel-art game.

**Comment by finscn** [comment]
@matrixreal , updated.

```
var n=new Ejecta.LocalNotification();
setTimeout(function(){
    n.schedule(1,"title","message", 10);
    console.log("LocalNotification has scheduled, please exit App.");
},5000);
```

**Comment by matrixreal** [comment]
ohh thats so amazing it work better than original 
however what mean these value ?

the "1" here 
setTimeout(function(){
    n.schedule(1,"title","message", 10); 

and here the "5000"
    console.log("LocalNotification has scheduled, please exit App.");
},5000); ?
thanks for reply

**Comment by finscn** [comment]
"1" is a id.   when you want to cancel a notification , you need  pass the id to cancel method.

Again,  
By the way , are you working in KetchApp ? If my game is done, could you publish it ? 
It's a pixel-art game. 
or Could you tell me how can I let my game be published with KetchApp

**Comment by matrixreal** [comment]
ok and what about the "5000" does ? (related with ?)
and for your game just skype me or send me email with screenshoots and i will do my best
i will feature your game because you done good work with me
thanks a lot for all

**Comment by finscn** [comment]
"5000" is ok. any Integer Number  is OK.

**Comment by matrixreal** [comment]
skype me "matrix.real" for your game

**Comment by matrixreal** [comment]
now i got this error with your lastest fork
2015-04-22 18:43:41.967 Ejecta[1472:60b] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIApplication registerUserNotificationSettings:]: unrecognized selector sent to instance 0x17e897a0'

**Comment by finscn** [comment]
my test is ok:

```
var n=new Ejecta.LocalNotification();
setTimeout(function(){
    n.schedule(1,"title","message", 10);
    console.log("LocalNotification has scheduled, please exit App.");
},1000);
```

what's your code ?

**Comment by matrixreal** [comment]
my code is
var n=new Ejecta.LocalNotification();
 n.schedule(1,"title","message", 60000);

**Comment by finscn** [comment]
what's your iOS version  ?

**Comment by matrixreal** [comment]
ios 7.X
and it work fine before you update "AlertView"
if i remove what you add and addwhat you remove it work fine

**Comment by finscn** [comment]
Thanks and I fixed it.  please pull new version

**Comment by matrixreal** [comment]
ok thanks but it will work on ios 8.X ?
since app review team always review our games ith ios 8 !!!

**Comment by finscn** [comment]
everything is ok

**Comment by matrixreal** [comment]
@finscn 
i just discover an 2 issues :
1-when the alert notification is shown and we cancel it there is no badge number
2-the alert notification are shown 6, 8 , times (probably the clear the previous notifications is not working)
thanks for fixing it

**Comment by matrixreal** [comment]
@finscn 
can you take a look on it please ?
thanks in advance

**Comment by matrixreal** [comment]
@finscn
any news ?
thanks

**Comment by finscn** [comment]
Sorry,   I can't  reproduce  these 2 bugs ,  @matrixreal 

Are you sure  there is no issue in your code?

Could you show me your code  about it ?

**Comment by matrixreal** [comment]
@finscn 
just set for example time for local notification 30 seconds
lunch the game, and close it quickly ....
the alert will show normally .... but there is no badge number on the icon !!!

after some minutes .... or later .... the local notification will be again shown ... 5 , 6 times 

my code is exactly like this fork

**Comment by finscn** [comment]
fixed .  Please test it .  Thanks :)

**Comment by matrixreal** [comment]
@finscn 
fixed 
but there are just 2 warning but work fine
![local1](https://cloud.githubusercontent.com/assets/6823974/8395262/67a00286-1d66-11e5-8015-1f7840c9c6fc.png)
xcode 6.2
ios 7.1.2

**Comment by finscn** [comment]
Fixed .  Please update.  Thanks
