### ISSUE TITLE
[suggestion]

### ISSUE THREAD

**Issue by matrixreal** [finscn/Ejecta#34]
@finscn 
hi
i would like to suggest to add the airpush sdk
they pay weekly and have very high ecpm (x3-x5 than admob)
really interesting company ... 
thanks

**Comment by finscn** [comment]
banner ad is no future , I think  reward video ad is more useful

**Comment by matrixreal** [comment]
Hi,
no future ? what you mean ?
thanks

**Comment by matrixreal** [comment]
hi,
any chance please ?
there is only 2 actions (show ad and hide ad)
i did try to figure it out but no success
thanks
