### ISSUE TITLE
Semantic Issue after xcode update 6.3.1

### ISSUE THREAD

**Issue by rungo73** [finscn/Ejecta#8]
Getting a semantic issue from line 61 in EJBindingCanvas.m after updating xcode to 6.3.1 when no issue reported previous version..

'Returning 'id<MTLTExture>' from a function with incompatible result type 'EJTexture*'

Is this a problem to publish?

**Comment by matrixreal** [comment]
i don't think so ...
but maybe @finscn  can do something

**Comment by finscn** [comment]
https://github.com/phoboslab/Ejecta/commit/45b35a71b69b50cf2805dea64212f2bd4b159f61

**Comment by rungo73** [comment]
That's great, thank you for pointing to fix.
